import React from 'react';
import { FiArrowRightCircle, FiPackage, FiFileText, FiDownload, FiCheck, FiX, FiAlertCircle, FiPrinter } from 'react-icons/fi';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import apiService from '../services/api';

const TransactionTable = ({ transactions, type = 'all' }) => {
    const apiBaseUrl = apiService.getBaseUrl();
    // Filter based on type if needed, though usually passed pre-filtered
    const displayData = type === 'all'
        ? transactions
        : transactions.filter(t =>
            type === 'material'
                ? (t.type === 'Material Purchase' || t.type === 'Material Return')
                : t.type === type
        );

    // Helper to get icon and color based on type
    const getTypeStyles = (txnType) => {
        switch (txnType) {
            case 'Payment In':
                return {
                    icon: <FiArrowRightCircle className="text-emerald-500" size={18} />,
                    bg: 'bg-emerald-50',
                    text: 'text-emerald-700',
                    border: 'border-emerald-100'
                };
            case 'Payment Out':
                return {
                    icon: <FiArrowRightCircle className="text-rose-500 rotate-180" size={18} />,
                    bg: 'bg-rose-50',
                    text: 'text-rose-700',
                    border: 'border-rose-100'
                };
            case 'Material Purchase':
                return {
                    icon: <FiPackage className="text-blue-500" size={18} />,
                    bg: 'bg-blue-50',
                    text: 'text-blue-700',
                    border: 'border-blue-100'
                };
            case 'Material Return':
                return {
                    icon: <FiPackage className="text-amber-500" size={18} />,
                    bg: 'bg-amber-50',
                    text: 'text-amber-700',
                    border: 'border-amber-100'
                };
            default:
                return {
                    icon: <FiFileText className="text-gray-500" size={18} />,
                    bg: 'bg-gray-50',
                    text: 'text-gray-700',
                    border: 'border-gray-100'
                };
        }
    };

    const generateReceipt = (tx) => {
        const doc = new jsPDF();

        // Company Header
        doc.setFontSize(20);
        doc.setTextColor(40, 40, 40);
        doc.text("NIRMAN TRACKER", 105, 15, { align: "center" });

        doc.setFontSize(10);
        doc.setTextColor(100, 100, 100);
        doc.text("Transaction Receipt", 105, 22, { align: "center" });

        // Receipt Details Table
        const receiptData = [
            ["Transaction ID", tx.id || "N/A"],
            ["Date", new Date(tx.date).toLocaleDateString()],
            ["Party Name", tx.party_name || "N/A"],
            ["Transaction Type", tx.type],
            ["Payment Method", tx.payment_method || "N/A"],
            ["Reference No", tx.reference_no || "-"],
            ["Amount", `Rs. ${parseFloat(tx.amount).toLocaleString(undefined, { minimumFractionDigits: 2 })}`],
            ["Description", tx.description || "-"]
        ];

        autoTable(doc, {
            startY: 30,
            head: [['Field', 'Details']],
            body: receiptData,
            theme: 'grid',
            headStyles: { fillColor: [66, 66, 66], textColor: 255, fontStyle: 'bold' },
            bodyStyles: { textColor: 50 },
            columnStyles: {
                0: { fontStyle: 'bold', cellWidth: 50 },
                1: { cellWidth: 'auto' }
            }
        });

        // Footer
        const pageHeight = doc.internal.pageSize.height;
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text("Generated by Nirman Tracker", 105, pageHeight - 10, { align: "center" });

        doc.save(`Receipt_${tx.id}_${tx.party_name}.pdf`);
    };

    if (!displayData || displayData.length === 0) {
        return (
            <div className="flex flex-col items-center justify-center py-12 px-4 bg-gray-50 rounded-xl border border-dashed border-gray-200 text-center">
                <div className="w-16 h-16 bg-white rounded-full flex items-center justify-center shadow-sm mb-4">
                    <FiFileText className="text-gray-300" size={32} />
                </div>
                <h3 className="text-lg font-bold text-gray-900 mb-1" style={{ fontFamily: 'var(--font-family)' }}>No Transactions Found</h3>
                <p className="text-sm text-gray-500 max-w-xs mx-auto" style={{ fontFamily: 'var(--font-family)' }}>
                    There are no {type !== 'all' ? type.toLowerCase() : ''} transactions recorded yet.
                </p>
            </div>
        );
    }

    return (
        <div className="overflow-hidden bg-white rounded-xl border border-gray-200 shadow-sm">
            <div className="overflow-x-auto">
                <table className="w-full">
                    <thead>
                        <tr className="bg-gray-50 border-b border-gray-100">
                            <th className="px-6 py-4 text-left text-xs font-bold text-gray-500 uppercase tracking-wider" style={{ fontFamily: 'var(--font-family)' }}>Date</th>
                            <th className="px-6 py-4 text-left text-xs font-bold text-gray-500 uppercase tracking-wider" style={{ fontFamily: 'var(--font-family)' }}>Party Details</th>
                            <th className="px-6 py-4 text-left text-xs font-bold text-gray-500 uppercase tracking-wider" style={{ fontFamily: 'var(--font-family)' }}>Transaction Type</th>
                            <th className="px-6 py-4 text-left text-xs font-bold text-gray-500 uppercase tracking-wider" style={{ fontFamily: 'var(--font-family)' }}>Reference</th>
                            <th className="px-6 py-4 text-right text-xs font-bold text-gray-500 uppercase tracking-wider" style={{ fontFamily: 'var(--font-family)' }}>Amount</th>
                            <th className="px-6 py-4 text-center text-xs font-bold text-gray-500 uppercase tracking-wider" style={{ fontFamily: 'var(--font-family)' }}>Receipt</th>
                        </tr>
                    </thead>
                    <tbody className="divide-y divide-gray-100">
                        {displayData.map((tx) => {
                            const styles = getTypeStyles(tx.type);
                            const isPositive = tx.type === 'Payment In' || tx.type === 'Material Return';
                            const formattedDate = new Date(tx.date).toLocaleDateString('en-GB', {
                                day: '2-digit',
                                month: 'short',
                                year: 'numeric'
                            });

                            return (
                                <tr key={tx.id} className="hover:bg-gray-50/80 transition-colors group">
                                    <td className="px-6 py-4 whitespace-nowrap">
                                        <span className="text-sm font-semibold text-gray-700" style={{ fontFamily: 'var(--font-family)' }}>
                                            {formattedDate}
                                        </span>
                                    </td>
                                    <td className="px-6 py-4">
                                        <div className="flex flex-col">
                                            <span className="text-sm font-bold text-gray-900" style={{ fontFamily: 'var(--font-family)' }}>{tx.party_name}</span>
                                            {tx.description && (
                                                <span className="text-xs text-gray-400 truncate max-w-[200px]" title={tx.description}>
                                                    {tx.description}
                                                </span>
                                            )}
                                        </div>
                                    </td>
                                    <td className="px-6 py-4 whitespace-nowrap">
                                        <div className={`inline-flex items-center gap-2 px-3 py-1.5 rounded-lg border ${styles.bg} ${styles.border}`}>
                                            {styles.icon}
                                            <span className={`text-xs font-bold uppercase tracking-wide ${styles.text}`} style={{ fontFamily: 'var(--font-family)' }}>
                                                {tx.type}
                                                {tx.payment_method && <span className="opacity-75"> • {tx.payment_method}</span>}
                                            </span>
                                        </div>
                                    </td>
                                    <td className="px-6 py-4 whitespace-nowrap">
                                        <span className="text-sm font-medium text-gray-600 bg-gray-100 px-2 py-1 rounded">
                                            {tx.reference_no || '-'}
                                        </span>
                                    </td>
                                    <td className="px-6 py-4 whitespace-nowrap text-right">
                                        <span className={`text-sm font-black ${isPositive ? 'text-emerald-600' : 'text-rose-600'}`} style={{ fontFamily: 'var(--font-family)' }}>
                                            {isPositive ? '+' : '-'} ₹ {parseFloat(tx.amount).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
                                        </span>
                                    </td>
                                    <td className="px-6 py-4 whitespace-nowrap text-center">
                                        <div className="flex items-center justify-center gap-2">
                                            {tx.attachment && (
                                                <a
                                                    href={`${apiBaseUrl}/${tx.attachment}`}
                                                    target="_blank"
                                                    rel="noopener noreferrer"
                                                    className="inline-flex items-center justify-center w-8 h-8 rounded-full bg-blue-50 text-blue-600 hover:bg-blue-100 hover:text-blue-700 transition-colors"
                                                    title="View Attachment"
                                                >
                                                    <FiDownload size={16} />
                                                </a>
                                            )}
                                            <button
                                                onClick={() => generateReceipt(tx)}
                                                className="inline-flex items-center justify-center w-8 h-8 rounded-full bg-gray-50 text-gray-600 hover:bg-gray-100 hover:text-gray-800 transition-colors"
                                                title="Download Receipt"
                                            >
                                                <FiPrinter size={16} />
                                            </button>
                                        </div>
                                    </td>
                                </tr>
                            );
                        })}
                    </tbody>
                </table>
            </div>
        </div>
    );
};

export default TransactionTable;
